version: "3"

services:
    server:
        container_name: dropby_backend
        image: dropby_backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./:/usr/src/app
        restart: on-failure
        env_file:
            - .env
